#!/bin/bash

echo "Resetting dunst..."
echo ">   Killing any active dunst instance"

RUNNING=`ps aux |  grep -ve "grep" | grep -o dunst`
if [ -z $RUNNING ] ; then
  echo ">   dunst is not running"
else
  killall dunst
  echo ">   killed dunst instance"
fi
#killall gnome-shell 
#MONITORCOUNT=`swaymsg -t get_outputs | grep type | wc -l `
#NEWINDEX=$(( $MONITORCOUNT - 1 ))

#sed -i -r "s/(monitor =).*/\1 $NEWINDEX/"  /home/tholian/.config/dunst/dunstrc
echo -e ">   Restarting dunst"
dunst -verbosity mesg --startup-notification >> /home/tholian/sway.log 2>&1 & 

echo -e ">   dunst reset complete!\n\n" 
