#!/bin/bash

#export WAYLAND_DISPLAY=wayland-0 && \
export XDG_SESSION_TYPE=wayland && \
rstudio \
  --disable-features=UseChromeOSDirectVideoDecoder \
  --ozone-platform-hint=auto \
  --use-gl=angle \
  --use-angle=gles \
  --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,WaylandWindowDecorations,WebRTCPipeWireCapturer,CanvasOopRasterization \
  --enable-gpu-rasterization \
  --enable-accelerated-2d-canvas \
  --enable-zero-copy \
  --enable-gpu-memory-buffer-compositor-resources \
  --enable-gpu-memory-buffer-video-frames \
  --enable-unsafe-webgpu \
  --enable-drdc \
  --back-forward-cache \
  
  
# Optional and alternative flags that do not cause issues not sure if they help

  # --use-angle=gl \
  # --ignore-gpu-blocklist \
  # --disable-gpu-sandbox \
  # --disable-gpu-driver-bug-workarounds \
  # --main-thread-compositing-priority \
  # --canvas-oop-rasterization \
  # --ui-enable-shared-image-cache-for-gpu \


# Flags known to result in errors but RStudio still loads
  
  # --enable-native-gpu-memory-buffers \


# Direct Rendering Display Compositor cannot be enabled properly
 
  # --enable-features=DirectRenderingDisplayCompositor \


# Vulkan can be enabled but doesn't work right, it throws a skia error that vulkan surface was not created, it breaks all other hardware accelaration 
#

  # --vulkan \
  # --use-angle=swiftshader \ 
  # --enable-vulkan-protected-memory \
  # --enable-features=Vulkan,UseChromeOSDirectVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE \
  # --use-vulkan=native \


# Skia graphite cannot be enabled it throws a bunch of errors, overrides enabling vulkan and disables it. 

  # --enable-features=SkiaGraphite \ 
  # --enable-skia-graphite \
  # --skia-graphite-backend=dawn \


# RawDraw Breaks the system
  # --enable-features=RawDraw


# These flags are on the internet but I doubt they do anything, they might be just obsolete. I checked it against this extensive list that is being updated regularly. https://peter.sh/experiments/chromium-command-line-switches/ and https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/about_flags.cc

  # --enable-gpu-compositing \
  # --enable-accelerated-video-decode \
  # --use-client-gmb-interface \
  # --memory-saver-multi-state-mode \
  # --use-gpu-scheduler-dfs \
  # --enable-webrtc-hw-decoding \
  # --enable-webrtc-hw-encoding \
