#!/bin/bash

#export WAYLAND_DISPLAY=wayland-0 && \
export XDG_SESSION_TYPE=wayland && \
rstudio \
  --disable-features=UseChromeOSDirectVideoDecoder \
  --ozone-platform-hint=auto \
  --use-gl=angle \
  --use-angle=gles \
  --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,WaylandWindowDecorations,WebRTCPipeWireCapturer,CanvasOopRasterization \
  --enable-gpu-rasterization \
  --enable-gpu-compositing \
  --enable-accelerated-2d-canvas \
  --enable-accelerated-video-decode \
  --enable-zero-copy \
  --main-thread-compositing-priority \
  --use-client-gmb-interface \
  --back-forward-cache \
  --canvas-oop-rasterization \
  --memory-saver-multi-state-mode \
  --ui-enable-shared-image-cache-for-gpu \
  --use-gpu-scheduler-dfs \
  --enable-gpu-memory-buffer-compositor-resources \
  --enable-gpu-memory-buffer-video-frames \
  --enable-webrtc-hw-decoding \
  --enable-webrtc-hw-encoding \
  --enable-unsafe-webgpu \

  
# Optional and alternative flags that do not cause issues

  # --use-angle=gl \
  # --ignore-gpu-blocklist \
  # --disable-gpu-sandbox \
  # --disable-gpu-driver-bug-workarounds \


# Flags known to result in errors but RStudio still loads
  
  # --enable-native-gpu-memory-buffers \


# Direct Rendering Display Compositor cannot be enabled properly

  # --enable-drdc \ 
  # --enable-features=DirectRenderingDisplayCompositor \


# Vulkan can be enabled but doesn't work right, it throws a skia error that vulkan surface was not created, it breaks all other hardware accelaration 
#

  # --vulkan \
  # --use-angle=swiftshader \ 
  # --enable-vulkan-protected-memory \
  # --enable-features=Vulkan,UseChromeOSDirectVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE \
  # --use-vulkan=native \


# Skia graphite cannot be enabled it throws a bunch of errors, overrides enabling vulkan and disables it. 

  # --enable-features=SkiaGraphite \ #this
  # --enable-skia-graphite \
  # --skia-graphite-backend=dawn \


# RawDraw Breaks the system
  # --enable-features=RawDraw

