#!/bin/bash

#export GDK_SCALE=2 
#export GDK_DPI_SCALE=0.5 
#export QT_AUTO_SCREEN_SCALE_FACTOR=1 
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=GNOME

zoom --enable-features=UseOzonePlatform --ozone-platform=wayland 
