#!/bin/bash


ARGS=$@

DEVICE="0:1:Power_Button"

case $ARGS in
  e | E | en | enable | EN | ENABLE | Enable )
    swaymsg input $DEVICE events enabled
    echo "Power button is enabled!"
    exit
    ;;
  d | D | dis | DIS | disable | DISABLE | Disable )
    swaymsg input $DEVICE events disabled
    echo "Power button is disabled!"
    exit
    ;;
  * )
    echo "Wrong input, use e to enable and d to disable."
    exit
    ;;
esac
